In [1]:
# Update sklearn to prevent version mismatches
#!pip install sklearn --upgrade

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
#!pip install joblib

In [52]:
import pandas as pd
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

Create a Random Sample Dataframe to get random an equal number of random values for white wine data
Red wine data has 1599 rows, and White wine data has 4898 rows

In [53]:
red_wine_df = pd.read_csv("winequality-red.csv", sep=';')
white_df = pd.read_csv("winequality-white.csv", sep=';')
white_wine_df = white_df.copy()
red_wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [54]:
#Remove quality of 9's, because only white wine data has five 9 qualities which would skew our data
new_white_df = white_wine_df[white_wine_df["quality"] <= 8].copy()
#get random sample
rand_white_df = new_white_df.sample(1599,random_state=2).reset_index(drop=True)
rand_white_df
#add color rows
rand_white_df["color"] = "white"
red_wine_df["color"] = "red"
# rand_white_df
# red_wine_df
new_combinedf = pd.concat([red_wine_df, rand_white_df,])
#red wine is 0 and white wine is 1
next_combinedf = pd.get_dummies(new_combinedf, columns=['color'])
next_combinedf = next_combinedf.drop(columns=["color_red"]).copy()
combinedf = next_combinedf.copy()
combinedf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color_white
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.40,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.80,5,0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.80,5,0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.80,6,0
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,4.6,0.445,0.00,1.4,0.053,11.0,178.0,0.99426,3.79,0.55,10.20,5,1
1595,6.0,0.170,0.33,6.0,0.036,30.0,111.0,0.99362,3.32,0.58,10.15,7,1
1596,7.6,0.300,0.27,10.6,0.039,31.0,119.0,0.99815,3.27,0.30,9.30,6,1
1597,6.8,0.270,0.35,7.8,0.048,76.0,197.0,0.99590,3.24,0.43,9.50,6,1
1598,5.9,0.240,0.34,2.0,0.037,40.0,108.0,0.98948,3.19,0.50,12.30,6,1

In [55]:
combinedf = combinedf.loc[\
(combinedf["quality"] < 9 ) & \
(combinedf["quality"] > 3 )  \
] 
combinedf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color_white
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.40,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.80,5,0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.80,5,0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.80,6,0
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,4.6,0.445,0.00,1.4,0.053,11.0,178.0,0.99426,3.79,0.55,10.20,5,1
1595,6.0,0.170,0.33,6.0,0.036,30.0,111.0,0.99362,3.32,0.58,10.15,7,1
1596,7.6,0.300,0.27,10.6,0.039,31.0,119.0,0.99815,3.27,0.30,9.30,6,1
1597,6.8,0.270,0.35,7.8,0.048,76.0,197.0,0.99590,3.24,0.43,9.50,6,1
1598,5.9,0.240,0.34,2.0,0.037,40.0,108.0,0.98948,3.19,0.50,12.30,6,1

In [56]:
# df1 = pd.read_csv("winequality-white.csv", sep=';')
# df2 = pd.read_csv("winequality-red.csv", sep=';')
# combinedf = pd.concat([df1,df2])
# combinedf = combinedf.dropna(axis='columns', how='all')
# # Drop the null rows
# combinedf = combinedf.dropna()
# combinedf.head()

In [57]:
combinedf.groupby('quality').count()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color_white
quality,,,,,,,,,,,,
4,109,109,109,109,109,109,109,109,109,109,109,109
5,1133,1133,1133,1133,1133,1133,1133,1133,1133,1133,1133,1133
6,1347,1347,1347,1347,1347,1347,1347,1347,1347,1347,1347,1347
7,513,513,513,513,513,513,513,513,513,513,513,513
8,81,81,81,81,81,81,81,81,81,81,81,81

# Select your features (columns)

In [58]:
# Set features. Drop koi disposition, y value. 
X = combinedf.drop(columns='quality')
#X = df.drop(columns='quality')
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color_white
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0

# Create a Train Test Split

Use `quality` for the y values

In [59]:
from sklearn.model_selection import train_test_split
#80% train, 20% test. y is this one column
#y = df['quality']
y = combinedf['quality']
#random state 42 will have same picks for x test and y test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y, test_size=0.1)

In [60]:
X_train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color_white
938,7.2,0.38,0.38,2.8,0.068,23.0,42.0,0.99356,3.34,0.72,12.9,0
463,8.1,0.66,0.70,2.2,0.098,25.0,129.0,0.99720,3.08,0.53,9.0,0
1537,5.4,0.58,0.08,1.9,0.059,20.0,31.0,0.99484,3.50,0.64,10.2,0
1522,6.1,0.32,0.25,2.3,0.071,23.0,58.0,0.99633,3.42,0.97,10.6,0
1584,6.7,0.32,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,0

# Pre-processing

Scale the data using LabelEncoder and MinMaxScaler

In [61]:
# Scale your data - see Activity 03/05
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [62]:
import tensorflow as tf
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.callbacks import EarlyStopping

In [63]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [64]:
y_train_categorical.shape

(2864, 5)

# Train the Model

In [67]:
# first, create a normal neural network with 11 inputs, 100 hidden nodes, and 3 outputs
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=12))
model.add(Dense(units=1000, activation='relu'))
model.add(Dense(units=10000, activation='relu'))
model.add(Dense(units=5, activation='softmax'))

In [68]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [69]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_29 (Dense)             (None, 100)               1300
_________________________________________________________________
dense_30 (Dense)             (None, 1000)              101000
_________________________________________________________________
dense_31 (Dense)             (None, 10000)             10010000
_________________________________________________________________
dense_32 (Dense)             (None, 5)                 50005
=================================================================
Total params: 10,162,305
Trainable params: 10,162,305
Non-trainable params: 0
_________________________________________________________________

In [70]:
# set early stopping as callback
callbacks = [EarlyStopping(monitor='val_loss', patience=2)]
model.fit(
    X_train_scaled,
    y_train_categorical,
    callbacks=callbacks,
    epochs=60,
    shuffle=True,
    verbose=2
)

Epoch 1/60
 - 8s - loss: 1.2725 - accuracy: 0.4141
Epoch 2/60

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning

 - 8s - loss: 1.2171 - accuracy: 0.4399
Epoch 3/60
 - 8s - loss: 1.0765 - accuracy: 0.5300
Epoch 4/60
 - 8s - loss: 1.0564 - accuracy: 0.5433
Epoch 5/60
 - 8s - loss: 1.0416 - accuracy: 0.5419
Epoch 6/60
 - 8s - loss: 1.0325 - accuracy: 0.5517
Epoch 7/60
 - 8s - loss: 1.0395 - accuracy: 0.5541
Epoch 8/60
 - 8s - loss: 1.0340 - accuracy: 0.5506
Epoch 9/60
 - 8s - loss: 1.0286 - accuracy: 0.5632
Epoch 10/60
 - 8s - loss: 1.0308 - accuracy: 0.5576
Epoch 11/60
 - 8s - loss: 1.0264 - accuracy: 0.5628
Epoch 12/60
 - 8s - loss: 1.0229 - accuracy: 0.5594
Epoch 13/60
 - 8s - loss: 1.0178 - accuracy: 0.5628
Epoch 14/60
 - 8s - loss: 1.0309 - accuracy: 0.5443
Epoch 15/60
 - 8s - loss: 1.0149 - accuracy: 0.5695
Epoch 16/60
 - 9s - loss: 1.0144 - accuracy: 0.5587
Epoch 17/60
 - 9s - loss: 1.0107 - accuracy: 0.5702
Epoch 18/60
 - 9s - loss: 1.0127 - accuracy: 0.5653
Epoch 19/60
 - 8s - loss: 1.0100 - accuracy: 0.5628
Epoch 20/60
 - 8s - loss: 1.0110 - accuracy: 0.5649
Epoch 21/60
 - 8s - loss: 1.0059 - accuracy: 0.5691
Epoch 22/60
 - 8s - loss: 1.0030 - accuracy: 0.5702
Epoch 23/60
 - 8s - loss: 1.0055 - accuracy: 0.5611
Epoch 24/60
 - 8s - loss: 0.9990 - accuracy: 0.5677
Epoch 25/60
 - 8s - loss: 0.9961 - accuracy: 0.5782
Epoch 26/60
 - 9s - loss: 0.9988 - accuracy: 0.5695
Epoch 27/60
 - 9s - loss: 0.9994 - accuracy: 0.5622
Epoch 28/60
 - 9s - loss: 0.9940 - accuracy: 0.5688
Epoch 29/60
 - 9s - loss: 0.9889 - accuracy: 0.5646
Epoch 30/60
 - 9s - loss: 0.9913 - accuracy: 0.5747
Epoch 31/60
 - 9s - loss: 0.9878 - accuracy: 0.5723
Epoch 32/60
 - 9s - loss: 0.9876 - accuracy: 0.5705
Epoch 33/60
 - 8s - loss: 0.9866 - accuracy: 0.5758
Epoch 34/60
 - 9s - loss: 0.9911 - accuracy: 0.5789
Epoch 35/60
 - 9s - loss: 0.9840 - accuracy: 0.5807
Epoch 36/60
 - 8s - loss: 0.9773 - accuracy: 0.5772
Epoch 37/60
 - 9s - loss: 0.9837 - accuracy: 0.5695
Epoch 38/60
 - 8s - loss: 0.9785 - accuracy: 0.5719
Epoch 39/60
 - 8s - loss: 0.9711 - accuracy: 0.5821
Epoch 40/60
 - 8s - loss: 0.9761 - accuracy: 0.5709
Epoch 41/60
 - 8s - loss: 0.9708 - accuracy: 0.5796
Epoch 42/60
 - 8s - loss: 0.9765 - accuracy: 0.5758
Epoch 43/60
 - 8s - loss: 0.9698 - accuracy: 0.5761
Epoch 44/60
 - 8s - loss: 0.9661 - accuracy: 0.5786
Epoch 45/60
 - 9s - loss: 0.9669 - accuracy: 0.5800
Epoch 46/60
 - 8s - loss: 0.9696 - accuracy: 0.5772
Epoch 47/60
 - 8s - loss: 0.9637 - accuracy: 0.5814
Epoch 48/60
 - 8s - loss: 0.9608 - accuracy: 0.5834
Epoch 49/60
 - 8s - loss: 0.9589 - accuracy: 0.5779
Epoch 50/60
 - 9s - loss: 0.9571 - accuracy: 0.5841
Epoch 51/60
 - 9s - loss: 0.9641 - accuracy: 0.5814
Epoch 52/60
 - 9s - loss: 0.9576 - accuracy: 0.5772
Epoch 53/60
 - 9s - loss: 0.9522 - accuracy: 0.5838
Epoch 54/60
 - 9s - loss: 0.9524 - accuracy: 0.5800
Epoch 55/60
 - 9s - loss: 0.9488 - accuracy: 0.5814
Epoch 56/60
 - 9s - loss: 0.9474 - accuracy: 0.5852
Epoch 57/60
 - 8s - loss: 0.9498 - accuracy: 0.5761
Epoch 58/60
 - 8s - loss: 0.9462 - accuracy: 0.5908
Epoch 59/60
 - 8s - loss: 0.9440 - accuracy: 0.5859
Epoch 60/60
 - 9s - loss: 0.9514 - accuracy: 0.5824

In [71]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 1.0042190355566976, Accuracy: 0.5078369975090027

In [73]:
encoded_predictions = model.predict_classes(X_test_scaled[:20])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [74]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:20])}")

Predicted classes: [5 6 6 5 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6]
Actual Labels: [5, 6, 7, 6, 6, 6, 7, 7, 5, 5, 6, 7, 6, 6, 6, 5, 6, 7, 6, 6]

# RESULTS

quality = 5,6,7

test size = .1

model.add(Dense(units=100, activation='relu', input_dim=11))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

Normal Neural Network - Loss: 0.816428262801847, Accuracy: 0.6056105494499207

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
# import joblib
# filename = 'redwinedeeplearning.sav'
# joblib.dump(model, filename)